# Generated by Django 3.2.4 on 2021-07-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='for_contact',
        ),
        migrations.DeleteModel(
            name='PhoneInfo',
        ),
    ]
