# Generated by Django 3.2.4 on 2021-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210724_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка на TikTok аккаунт')),
                ('icon', models.ImageField(default='', upload_to='media', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'TikTok',
                'verbose_name_plural': 'TikTok',
            },
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка на YouTube аккаунт')),
                ('icon', models.ImageField(default='', upload_to='media', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'YouTube',
                'verbose_name_plural': 'YouTube',
            },
        ),
        migrations.AddField(
            model_name='facebook',
            name='icon',
            field=models.ImageField(default='', upload_to='media', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='icon',
            field=models.ImageField(default='', upload_to='media', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='icon',
            field=models.ImageField(default='', upload_to='media', verbose_name='Иконка'),
        ),
    ]
