# Generated by Django 3.2.4 on 2021-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210724_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='icon',
            field=models.ImageField(upload_to='media', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='icon',
            field=models.ImageField(upload_to='media', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='icon',
            field=models.ImageField(upload_to='media', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='icon',
            field=models.ImageField(upload_to='media', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='icon',
            field=models.ImageField(upload_to='media', verbose_name='Иконка'),
        ),
    ]
