# Generated by Django 3.2.4 on 2021-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.TextField(verbose_name='Кейс для фирмы')),
                ('case_img', models.ImageField(upload_to='media', verbose_name='Баннер кейса')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Результат работы', 'verbose_name_plural': 'Результаты работы'},
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Главный баннер', 'verbose_name_plural': 'Главные баннеры'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='worksteps',
            options={'verbose_name': 'Этапы работы', 'verbose_name_plural': 'Этапы работы'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_logo',
        ),
    ]
