# Generated by Django 3.2.4 on 2021-07-01 12:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210701_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='worksteps',
            options={'verbose_name': 'Этап работы', 'verbose_name_plural': 'Этапы работы'},
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='main_banner_image',
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='main_banner_background_image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка заднего фона главного баннера'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='main_banner_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_value',
            field=models.DecimalField(decimal_places=0, max_digits=10000, verbose_name='Результативное число'),
        ),
        migrations.AlterField(
            model_name='worksteps',
            name='workstep_number',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Этап работы (число)'),
        ),
    ]
