# Generated by Django 3.2.4 on 2021-07-08 08:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20210701_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_img', models.ImageField(upload_to='media', verbose_name='Баннер кейса')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='CaseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=200, verbose_name='Кейс для фирмы')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='main_banner_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет главного баннера'),
        ),
        migrations.AddField(
            model_name='caseimages',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_page.casetitle', verbose_name='Для кейса'),
        ),
    ]
