# Generated by Django 3.2.4 on 2021-07-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20210708_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casetitle',
            old_name='case_title',
            new_name='title',
        ),
    ]
