# Generated by Django 3.2.4 on 2021-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_rename_case_title_casetitle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок результата'),
        ),
    ]
