# Generated by Django 3.2.4 on 2021-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20210709_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_title', models.CharField(max_length=200, verbose_name='Название соц. сети')),
                ('link', models.TextField(verbose_name='Ссылка на соц. сеть')),
                ('icon', models.ImageField(upload_to='media', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Контактную информацию',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контактную информацию', 'verbose_name_plural': 'Контактная информация'},
        ),
    ]
