# Generated by Django 3.2.4 on 2021-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20210709_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetworks',
            options={'verbose_name': 'Соц. сеть', 'verbose_name_plural': 'Соц. сети'},
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='main_banner_background_image',
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='main_banner_color',
        ),
        migrations.RemoveField(
            model_name='mainbanner',
            name='main_banner_gif',
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='main_banner_logo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка для баннера'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='main_banner_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок главного баннера'),
        ),
    ]
