# Generated by Django 3.2.4 on 2021-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20210712_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksteps',
            name='workstep_title',
            field=models.CharField(default='', max_length=500, verbose_name='Заголовок этапа работы'),
        ),
    ]
