# Generated by Django 3.2.4 on 2021-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_worksteps_workstep_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksteps',
            name='workstep_title',
            field=models.CharField(max_length=500, verbose_name='Заголовок этапа работы'),
        ),
    ]
