# Generated by Django 3.2.4 on 2021-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_worksteps_workstep_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='SocialNetworks',
        ),
    ]
