# Generated by Django 3.2.4 on 2021-07-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20210724_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseimages',
            old_name='case_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='counter_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='mainbanner',
            old_name='main_banner_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='mainbanner',
            old_name='main_banner_subtitle',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='mainbanner',
            old_name='main_banner_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='worksteps',
            old_name='workstep_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='worksteps',
            old_name='workstep_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='worksteps',
            old_name='workstep_title',
            new_name='title',
        ),
    ]
