# Generated by Django 3.2.4 on 2021-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20210724_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
