# Generated by Django 3.2.4 on 2021-08-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_auto_20210724_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
