# Generated by Django 3.2.4 on 2021-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_metatags'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksteps',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок этапа работы'),
        ),
    ]
