# Generated by Django 3.2.4 on 2021-07-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperate_title', models.CharField(max_length=300, verbose_name='Название компании')),
                ('cooperate_img', models.ImageField(upload_to='media', verbose_name='Лого компании')),
            ],
            options={
                'verbose_name': 'Партнёра',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок главного баннера для "Разработки Сайтов"')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок главного баннера для "Разработки Сайтов"')),
                ('logo', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка баннера для "Разработки Сайтов"')),
            ],
            options={
                'verbose_name': 'Главный баннер для "Разработки Сайтов"',
                'verbose_name_plural': 'Главные баннеры для "Разработки Сайтов"',
            },
        ),
        migrations.CreateModel(
            name='MiniBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_banner_img', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка мини-баннера для "Разработки Сайтов"')),
                ('mobile_mini_banner_img', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка мини-баннера для мобильных устройств')),
            ],
            options={
                'verbose_name': 'Мини-баннер для "Разработки Сайтов"',
                'verbose_name_plural': 'Мини-баннеры для "Разработки Сайтов"',
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_title', models.CharField(max_length=250, verbose_name='Название тарифа')),
                ('tariff_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='TariffList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_list', models.CharField(max_length=250, verbose_name='Что в себя включает?')),
                ('tariff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webdev.tariffs', verbose_name='Для тарифа')),
            ],
            options={
                'verbose_name': 'Список услуг',
                'verbose_name_plural': 'Список услуг',
            },
        ),
    ]
