# Generated by Django 3.2.4 on 2021-07-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperate',
            old_name='cooperate_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='cooperate',
            old_name='cooperate_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='minibanner',
            old_name='mini_banner_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='minibanner',
            old_name='mobile_mini_banner_img',
            new_name='mobile_img',
        ),
        migrations.RenameField(
            model_name='tarifflist',
            old_name='tariff_list',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='tariffs',
            old_name='tariff_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='tariffs',
            old_name='tariff_title',
            new_name='title',
        ),
    ]
