# Generated by Django 3.2.4 on 2021-07-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0002_auto_20210724_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooperate',
        ),
    ]
