# Generated by Django 3.2.4 on 2021-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название компании')),
                ('img', models.ImageField(upload_to='media', verbose_name='Лого компании')),
            ],
            options={
                'verbose_name': 'Партнёра',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
