# Generated by Django 3.2.4 on 2021-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_strategy', '0002_worksteps_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksteps',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок этапа работы'),
        ),
    ]
