# Generated by Django 3.2.4 on 2021-07-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_strategy', '0003_alter_worksteps_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksteps',
            name='number',
        ),
    ]
