# Generated by Django 3.2.4 on 2021-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_strategy', '0005_metatags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksteps',
            name='text',
            field=models.TextField(blank=True, verbose_name='Этап работы (текст)'),
        ),
    ]
