# Generated by Django 3.2.4 on 2021-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksteps',
            name='step',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Этап работы (номер)'),
        ),
    ]
