# Generated by Django 3.2.4 on 2021-08-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandbook', '0003_alter_tariffs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='bonus',
            field=models.CharField(blank=True, max_length=400, verbose_name='Бонусы при приобретении этого тарифа'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price',
            field=models.CharField(default='0', max_length=11, verbose_name='Цена'),
        ),
    ]
