# Generated by Django 3.2.4 on 2021-08-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandbook', '0004_auto_20210806_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffs',
            name='bonus',
        ),
    ]
