# Generated by Django 3.2.4 on 2021-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandbook', '0005_remove_tariffs_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksteps',
            name='step',
        ),
        migrations.AddField(
            model_name='worksteps',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Заголовок этапа работы'),
        ),
        migrations.AlterField(
            model_name='worksteps',
            name='text',
            field=models.TextField(default='', verbose_name='Этап работы (текст)'),
        ),
    ]
