# Generated by Django 3.2.4 on 2021-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandbook', '0006_auto_20210806_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksteps',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Этап работы (текст)'),
        ),
    ]
