# Generated by Django 3.2.4 on 2021-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperate',
            options={'verbose_name': 'Сотрудничество', 'verbose_name_plural': 'Сотрудничество'},
        ),
        migrations.AddField(
            model_name='minibanner',
            name='mobile_mini_banner_img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка мини-баннера для мобильных устройств'),
        ),
    ]
