# Generated by Django 3.2.4 on 2021-07-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0002_auto_20210724_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperate',
            options={'verbose_name': 'Партнёра', 'verbose_name_plural': 'Партнёры'},
        ),
    ]
