# Generated by Django 3.2.4 on 2021-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0005_delete_cooperate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Главный баннер', 'verbose_name_plural': 'Главные баннеры'},
        ),
        migrations.AlterModelOptions(
            name='minibanner',
            options={'verbose_name': 'Мини-баннер', 'verbose_name_plural': 'Мини-баннеры'},
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='minibanner',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Мини-баннер'),
        ),
        migrations.AlterField(
            model_name='minibanner',
            name='mobile_img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Мини-баннер для мобильных устройств'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
