# Generated by Django 3.2.4 on 2021-08-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favicon',
        ),
        migrations.DeleteModel(
            name='MetaTags',
        ),
    ]
