# Generated by Django 3.2.4 on 2021-08-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0002_auto_20210804_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, upload_to='media', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicon',
            },
        ),
    ]
