# Generated by Django 3.2.4 on 2021-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(verbose_name='HTML-Код, для <head> элемента')),
                ('main_page_tag', models.TextField(verbose_name='HTML-Код, для <head> для главной страницы (ЯМетрика/GAnalytics/etc...)')),
            ],
            options={
                'verbose_name': 'Тэг для <head>',
                'verbose_name_plural': 'Тэги для <head>',
            },
        ),
    ]
