# Generated by Django 3.2.4 on 2021-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_headtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headtags',
            name='main_page_tag',
            field=models.TextField(blank=True, verbose_name='HTML-Код, для <head> для главной страницы (ЯМетрика/GAnalytics/etc...)'),
        ),
    ]
