# Generated by Django 3.2.4 on 2021-08-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_headtags_main_page_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='headtags',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Для чего этот тэг?'),
        ),
        migrations.AlterField(
            model_name='headtags',
            name='tag',
            field=models.TextField(blank=True, verbose_name='HTML-Код, для <head> элемента'),
        ),
    ]
