# Generated by Django 3.2.4 on 2021-08-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20210810_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headtags',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Для чего этот тэг?'),
        ),
    ]
