# Generated by Django 3.2.4 on 2021-07-26 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contextadv', '0002_contextadvertisementtools'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextAdvertisementDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название инструмента')),
                ('description', models.TextField(verbose_name='Описание инструмента')),
            ],
            options={
                'verbose_name': 'Описание инструмента контекстной рекламы',
                'verbose_name_plural': 'Описание инструментов контекстной рекламы',
            },
        ),
        migrations.CreateModel(
            name='ContextAdvertisementPossibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibilities', models.CharField(max_length=300, verbose_name='Возможность инструмента')),
                ('for_tool', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contextadv.contextadvertisementdescription', verbose_name='Для инструмента')),
            ],
            options={
                'verbose_name': 'Возможности инструмента контекстной рекламы',
                'verbose_name_plural': 'Возможности инструментов контекстной рекламы',
            },
        ),
    ]
