# Generated by Django 3.2.4 on 2021-07-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contextadv', '0003_contextadvertisementdescription_contextadvertisementpossibilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextadvertisementpossibilities',
            options={'verbose_name': 'Возможность инструмента контекстной рекламы', 'verbose_name_plural': 'Возможности инструментов контекстной рекламы'},
        ),
        migrations.RenameField(
            model_name='contextadvertisementpossibilities',
            old_name='for_tool',
            new_name='tool',
        ),
    ]
