# Generated by Django 3.2.4 on 2021-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextadv', '0005_metatags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextadvertisementdescription',
            name='description',
            field=models.TextField(verbose_name='Описание инструмента\n\n(для переноса строки использовать <br>)'),
        ),
    ]
