# Generated by Django 3.2.4 on 2021-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_metatags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок этапа работы')),
                ('text', models.TextField(blank=True, verbose_name='Этап работы (текст)')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
            },
        ),
    ]
